# Generated by Django 5.1.3 on 2025-02-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customorder',
            options={'verbose_name': 'CustomOrder', 'verbose_name_plural': 'CustomOrder'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'MyCustomOrder', 'verbose_name_plural': 'MyCustomOrders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'MyCustomOrderItem', 'verbose_name_plural': 'MyCustomOrderItems'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'MyPaymentMethod', 'verbose_name_plural': 'MyPaymentMethods'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('-created_at',), 'verbose_name': 'MyPrice', 'verbose_name_plural': 'MyPrices'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'CustomProduct', 'verbose_name_plural': 'CustomProducts'},
        ),
        migrations.AlterModelOptions(
            name='producttag',
            options={'ordering': ('-created_at',), 'verbose_name': 'CustomProductTag', 'verbose_name_plural': 'CustomProductTags'},
        ),
        migrations.AlterModelTable(
            name='customorder',
            table='custom_orders',
        ),
        migrations.AlterModelTable(
            name='order',
            table='my_orders',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='my_custom_order_items',
        ),
        migrations.AlterModelTable(
            name='paymentmethod',
            table='my_payment_methods',
        ),
        migrations.AlterModelTable(
            name='price',
            table='my_prices',
        ),
        migrations.AlterModelTable(
            name='product',
            table='custom_products',
        ),
        migrations.AlterModelTable(
            name='producttag',
            table='custom_product_tags',
        ),
    ]
