# Generated by Django 5.1.3 on 2025-02-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
        ('dashboard', '0002_alter_country_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliateprogram',
            name='allowed_countries',
        ),
        migrations.AddField(
            model_name='affiliateprogram',
            name='allowed_regions',
            field=models.ManyToManyField(related_name='affiliate_program_countries', to='dashboard.region', verbose_name='Allowed Regions'),
        ),
    ]
