# Generated by Django 5.1.3 on 2025-02-06 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('payments', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Usage Count')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('referred_user_count', models.IntegerField(default=0, verbose_name='Referred User Count')),
                ('unique_url', models.URLField(blank=True, verbose_name='Unique URL')),
                ('campaign_source', models.CharField(blank=True, max_length=100, verbose_name='Campaign Source')),
                ('campaign_medium', models.CharField(blank=True, max_length=100, verbose_name='Campaign Medium')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_code_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Referral Code',
                'verbose_name_plural': 'Referral Codes',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ReferralAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.TextField(verbose_name='Action Taken')),
                ('action_date', models.DateField(verbose_name='Action Date')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('device_info', models.TextField(verbose_name='Device Info')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_audit_referral_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('referral_codes', models.ManyToManyField(related_name='referral_audit_referral_codes', to='referral.referralcode', verbose_name='Referral Codes')),
            ],
            options={
                'verbose_name': 'Referral Audit',
                'verbose_name_plural': 'Referral Audits',
                'ordering': ['-action_date'],
            },
        ),
        migrations.CreateModel(
            name='ReferralConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_date', models.DateField(verbose_name='Conversion Date')),
                ('conversion_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Conversion Value')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('reward_issued', models.BooleanField(default=False, verbose_name='Reward Issued')),
                ('conversion_source', models.CharField(max_length=50, verbose_name='Conversion Source')),
                ('referral_type', models.CharField(blank=True, max_length=50, verbose_name='Referral Type')),
                ('referral_codes', models.ManyToManyField(related_name='referral_conversion_referral_codes', to='referral.referralcode', verbose_name='Referral Codes')),
                ('referred_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_conversion_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Referral Conversation',
                'verbose_name_plural': 'Referral Conversations',
                'ordering': ['-conversion_date'],
            },
        ),
        migrations.CreateModel(
            name='ReferralEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_opened', models.BooleanField(default=False, verbose_name='Email Opened')),
                ('email_clicked', models.BooleanField(default=False, verbose_name='Email Clicked')),
                ('social_share_count', models.IntegerField(default=0, verbose_name='Social Share Count')),
                ('last_interaction_date', models.DateField(blank=True, null=True, verbose_name='Last Interaction Date')),
                ('referral_codes', models.ManyToManyField(related_name='referral_engagement_referral_codes', to='referral.referralcode', verbose_name='Referral Codes')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Referral Engagement',
                'verbose_name_plural': 'Referral Engagements',
                'ordering': ['-last_interaction_date'],
            },
        ),
        migrations.CreateModel(
            name='ReferralNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_sent', models.DateField(verbose_name='Date Sent')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('notification_type', models.CharField(max_length=50, verbose_name='Notification Type')),
                ('priority', models.CharField(max_length=50, verbose_name='Priority')),
                ('action_required', models.BooleanField(default=False, verbose_name='Action Required')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_notification_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Referral Notification',
                'verbose_name_plural': 'Referral Notifications',
                'ordering': ['-date_sent'],
            },
        ),
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('reward_type', models.CharField(max_length=50, verbose_name='Reward Type')),
                ('reward_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Reward Value')),
                ('currency', models.CharField(max_length=10, verbose_name='Currency')),
                ('min_referral_count', models.IntegerField(default=0, verbose_name='Min Referral Count')),
                ('max_referrals_per_user', models.IntegerField(default=100, verbose_name='Max Referrals Per User')),
                ('date_created', models.DateField(verbose_name='Date Created')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('program_duration', models.IntegerField(verbose_name='Program Duration')),
                ('target_industry', models.CharField(max_length=100, verbose_name='Target Industry')),
                ('allowed_regions', models.ManyToManyField(related_name='engagement_program_regions', to='dashboard.region', verbose_name='Allowed Regions')),
            ],
            options={
                'verbose_name': 'Referral Program',
                'verbose_name_plural': 'Referral Program',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='referralcode',
            name='programs',
            field=models.ManyToManyField(related_name='referral_code_programs', to='referral.referralprogram', verbose_name='Programs'),
        ),
        migrations.CreateModel(
            name='ReferralCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=255, verbose_name='Campaign Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('goal', models.TextField(verbose_name='Goal')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Budget')),
                ('spending_to_date', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Spending To Date')),
                ('target_audience', models.TextField(blank=True, verbose_name='Target Audience')),
                ('programs', models.ManyToManyField(related_name='referral_campaign_programs', to='referral.referralprogram', verbose_name='Programs')),
            ],
            options={
                'verbose_name': 'Referral Campaign',
                'verbose_name_plural': 'Referral Campaigns',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='ReferralBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_type', models.CharField(max_length=50, verbose_name='Bonus Type')),
                ('bonus_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bonus Value')),
                ('min_referrals_required', models.IntegerField(default=0, verbose_name='Min Referrals Required')),
                ('bonus_date', models.DateField(verbose_name='Bonus Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('max_usage', models.IntegerField(default=1, verbose_name='Max Usage')),
                ('eligibility_criteria', models.TextField(blank=True, verbose_name='Eligibility Criteria')),
                ('programs', models.ManyToManyField(related_name='referral_bonus_programs', to='referral.referralprogram', verbose_name='Programs')),
            ],
            options={
                'verbose_name': 'Referral Bonus',
                'verbose_name_plural': 'Referral Bonus',
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_given', models.BooleanField(default=False, verbose_name='Reward Given')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('referred', models.ManyToManyField(related_name='referrals_received', to=settings.AUTH_USER_MODEL, verbose_name='Referred')),
                ('referrer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL, verbose_name='Referrer')),
                ('program', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='referral.referralprogram', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
            },
        ),
        migrations.CreateModel(
            name='ReferralProgramPartecipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('reward_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Reward Earned')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=50, verbose_name='Status')),
                ('programs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_program_partecipation_programs', to='referral.referralprogram', verbose_name='Programs')),
                ('referral_codes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_program_partecipation_referral_codes', to='referral.referralcode', verbose_name='Referral Codes')),
            ],
            options={
                'verbose_name': 'Referral Program Partecipation',
                'verbose_name_plural': 'Referral Program Partecipations',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(max_length=50, verbose_name='Reward Type')),
                ('reward_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Reward Value')),
                ('date_awarded', models.DateField(verbose_name='Date Awarded')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('reward_description', models.TextField(blank=True, verbose_name='Reward Description')),
                ('reward_source', models.CharField(blank=True, max_length=100, verbose_name='Reward Source')),
                ('referral_codes', models.ManyToManyField(related_name='referra_reward_referral_codes', to='referral.referralcode', verbose_name='Referral Codes')),
                ('referred_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referra_reward_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Referral Reward',
                'verbose_name_plural': 'Referral Rewards',
                'ordering': ['-date_awarded'],
            },
        ),
        migrations.CreateModel(
            name='ReferralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_reward_type', models.CharField(max_length=50, verbose_name='Default Reward Type')),
                ('max_referrals_allowed', models.IntegerField(default=100, verbose_name='Max Referrals Allowed')),
                ('notification_preference', models.CharField(max_length=50, verbose_name='Notification Preference')),
                ('auto_share_setting', models.BooleanField(default=True, verbose_name='Auto Share Setting')),
                ('social_share_message', models.TextField(blank=True, verbose_name='Social Share Message')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referra_setting_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Referral Settings',
                'verbose_name_plural': 'Referral Settings',
            },
        ),
        migrations.CreateModel(
            name='ReferralStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50, verbose_name='Period')),
                ('click_count', models.IntegerField(default=0, verbose_name='Click Count')),
                ('conversion_count', models.IntegerField(default=0, verbose_name='Conversion Count')),
                ('total_rewards', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Rewards')),
                ('average_conversion_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Average Conversione Value')),
                ('highest_referral_earning', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Highest Referral Earning')),
                ('referral_codes', models.ManyToManyField(related_name='referra_stats_referral_codes', to='referral.referralcode', verbose_name='Referral Codes')),
            ],
            options={
                'verbose_name': 'Referral Stat',
                'verbose_name_plural': 'Referral Stats',
            },
        ),
        migrations.CreateModel(
            name='ReferralTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='Transaction Date')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(max_length=10, verbose_name='Currency')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('conversion_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Conversion Value')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Discount Value')),
                ('coupon_code_used', models.CharField(blank=True, max_length=100, verbose_name='Coupon Code Used')),
                ('channel', models.CharField(blank=True, max_length=50, verbose_name='Channel')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.order', verbose_name='Order')),
                ('referral_codes', models.ManyToManyField(related_name='referra_transaction_referral_codes', to='referral.referralcode', verbose_name='Referral Codes')),
                ('referred_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referra_transaction_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Referral Transaction',
                'verbose_name_plural': 'Referral Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='ReferralUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_referrals', models.IntegerField(default=0, verbose_name='Total Referrals')),
                ('active_referrals', models.IntegerField(default=0, verbose_name='Active Referrals')),
                ('inactive_referrals', models.IntegerField(default=0, verbose_name='Inactive Referrals')),
                ('total_rewards_earned', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Rewards Earned')),
                ('total_spent_by_referred_users', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Spent By Referred Users')),
                ('average_order_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Average Order Value')),
                ('loyalty_points_earned', models.IntegerField(default=0, verbose_name='Loyalty Points Earned')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referra_user_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Referral User',
                'verbose_name_plural': 'Referral Users',
            },
        ),
    ]
