# Generated by Django 5.1.3 on 2025-03-12 17:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0004_alter_referralbonus_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralbonus',
            name='expiry_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 4, 11), null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='expiry_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 4, 11), null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='referralreward',
            name='expiry_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 4, 11), null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='referraltransaction',
            name='referral_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referra_transaction_referral_code', to='referral.referralcode', verbose_name='Referral Code'),
        ),
        migrations.CreateModel(
            name='ReferralCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Commission Value')),
                ('commission_date', models.DateTimeField(auto_now_add=True, verbose_name='Commission Date')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50, verbose_name='Status')),
                ('trigger_event', models.CharField(blank=True, max_length=100, verbose_name='Trigger Event')),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Commission Percentage')),
                ('expiry_date', models.DateField(blank=True, default=None, null=True, verbose_name='Expiry Date')),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.referralcode', verbose_name='Referral Code')),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Referred User')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='referral.referraltransaction', verbose_name='Transaction ID')),
            ],
            options={
                'verbose_name': 'Referral Commission',
                'verbose_name_plural': 'Referral Commissions',
            },
        ),
    ]
