# Generated by Django 5.1.3 on 2025-02-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Nation', 'verbose_name_plural': 'Nations'},
        ),
    ]
