# Generated by Django 5.1.3 on 2025-02-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_platform',
            field=models.BooleanField(default=True),
        ),
    ]
