# Generated by Django 5.1.3 on 2025-02-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profile_is_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_platform',
            field=models.BooleanField(default=True, verbose_name='Is Platform'),
        ),
    ]
