# Generated by Django 5.1.3 on 2025-02-28 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_profile_is_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilebusiness',
            name='code',
            field=models.CharField(default='HREMFSD', max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='profilebusiness',
            name='status',
            field=models.CharField(default='inactive', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='profilebusiness',
            name='unique_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Invitation URL'),
        ),
        migrations.AddField(
            model_name='profilebusiness',
            name='user_registered',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_registered', to=settings.AUTH_USER_MODEL, verbose_name='User Registered'),
        ),
    ]
