# Generated by Django 5.1.3 on 2025-02-11 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeCustomerId', models.CharField(max_length=255)),
                ('stripeSubscriptionId', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StripeCustomer',
                'verbose_name_plural': 'StripeCustomers',
                'db_table': 'stripe_customers',
            },
        ),
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
                ('stripe_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.stripecustomer')),
            ],
            options={
                'verbose_name': 'StripeSubscription',
                'verbose_name_plural': 'StripeSubscriptions',
                'db_table': 'custom_stripe_subscriptions',
            },
        ),
    ]
