# Generated by Django 5.1.3 on 2025-02-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripecustomer',
            options={'verbose_name': 'StripeCustomer', 'verbose_name_plural': 'StripeCustomers'},
        ),
        migrations.RenameField(
            model_name='stripecustomer',
            old_name='stripeCustomerId',
            new_name='stripe_customer_id',
        ),
        migrations.RenameField(
            model_name='stripecustomer',
            old_name='stripeSubscriptionId',
            new_name='stripe_subscription_id',
        ),
        migrations.AlterModelTable(
            name='stripecustomer',
            table='stripe_customers',
        ),
    ]
