# Generated by Django 5.1.3 on 2025-02-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripecustomer',
            old_name='stripe_customer_id',
            new_name='stripeCustomerId',
        ),
        migrations.RenameField(
            model_name='stripecustomer',
            old_name='stripe_subscription_id',
            new_name='stripeSubscriptionId',
        ),
    ]
