# Generated by Django 5.1.3 on 2025-02-10 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_stripe_customer_id_stripecustomer_stripecustomerid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
                ('stripe_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.stripecustomer')),
            ],
            options={
                'verbose_name': 'StripeSubscription',
                'verbose_name_plural': 'StripeSubscriptions',
                'db_table': 'stripe_subscriptions',
            },
        ),
    ]
