# Generated by Django 5.1.3 on 2025-02-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='StripeSubscription',
        ),
    ]
