# Generated by Django 5.1.3 on 2025-03-09 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_onetimepurchase_stripe_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepurchase',
            name='user',
        ),
        migrations.AddField(
            model_name='onetimepurchase',
            name='stripe_customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='subscriptions.stripecustomer'),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='stripeCustomerId',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='stripeSubscriptionId',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
